# Generated by Django 4.1 on 2022-11-21 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("magicbook", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AI_Answer",
            new_name="AiAnswer",
        ),
    ]
