# Generated by Django 3.2.5 on 2022-10-10 19:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50, verbose_name='Username')),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50, verbose_name='Password')),
                ('api_keys', models.JSONField(blank=True, default=dict, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('titulo', models.TextField(max_length=200)),
                ('is_public', models.BooleanField(default=False)),
                ('title', models.TextField(max_length=400)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magicbook.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='AI_Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('prompt', models.TextField(max_length=600)),
                ('ans', models.JSONField(blank=True, default=dict, null=True)),
                ('params', models.JSONField(blank=True, default=dict, null=True)),
                ('dreamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='magicbook.dream')),
            ],
        ),
    ]
