# Generated by Django 4.1 on 2022-11-27 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("magicbook", "0002_alter_usuario_password"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dream",
            name="titulo",
        ),
    ]
