# Generated by Django 4.1 on 2022-11-27 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("magicbook", "0004_alter_dream_is_public"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dream",
            name="title",
            field=models.TextField(max_length=400, unique=True),
        ),
    ]
